# Generated by Django 2.2.2 on 2019-06-12 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='lineons',
            new_name='linenos',
        ),
    ]
