# Generated by Django 2.2.2 on 2019-06-12 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_auto_20190612_1555'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
