# Generated by Django 2.2.2 on 2019-06-09 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='linenos',
            new_name='lineons',
        ),
    ]
